name: build_uinput

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unraid_version: [6.9.2, 6.9.1, 6.8.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: gameonwhales/unraid-module-builder:latest
          options: |
            -v ${{ github.workspace }}/packages/uinput/config:/config
            -v ${{ github.workspace }}/kernel-bin/${{ matrix.unraid_version }}:/output
            -e UNRAID_VERSION=${{ matrix.unraid_version }}
          shell: bash
          run: /opt/scripts/build.sh
      
      - name: get built kernel version
        id: kernel-version
        run: echo "::set-output name=kernel::$(ls ${{ github.workspace }}/kernel-bin/${{ matrix.unraid_version }}/lib/modules/)"

      - name: Upload kernel modules for ${{ matrix.unraid_version }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.kernel-version.outputs.kernel }}
          path: ${{ github.workspace }}/kernel-bin/${{ matrix.unraid_version }}/lib/modules/${{ steps.kernel-version.outputs.kernel }}
  
  mk-pull-request:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download all built kernel modules
        uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/kernel-bin/

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GOWBot <gowbot@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          assignees: ${{ github.actor }}
          signoff: false
          branch: kernel-build
          branch-suffix: short-commit-hash
          delete-branch: true
          title: 'Generated kernel modules'
          body: 'Review the output modules and merge if everything looks fine.'
          commit-message: '[GITHUB ACTIONS]: adding built kernel modules'
